version: '3.9'

services:
  user:
    build: 
      context: .
    restart: on-failure
    ports:
      - 2200:2200 
      - 2201:2201
    depends_on:
      sql:
        condition: service_healthy

  sql:
    image: postgres:14.12
    ports:
      - 5432:5432
    environment:
      POSTGRES_ROOT_PASSWORD: root_password_here
      POSTGRES_DB: user
      POSTGRES_USER: svc_user
      POSTGRES_PASSWORD: some_password
    healthcheck: # https://docs.docker.com/engine/reference/builder/#healthcheck
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 3s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7.2.1
    ports:
      - 6379:6379