server:
  grpc:
    address: 0.0.0.0 # To run in host/k8s env
    # address: go-authentication # To run with docker
    port: 30100
  http:
    address: 0.0.0.0 # To run in host/k8s env
    # address: go-authentication # To run with docker
    port: 30101
    timeout: 30s
  logger:
    format: json
database:
  sql:
    driver: postgres
    host: localhost # To run in host machine
    # host: sql # To run within docker env
    # host: 10.100.168.1 # To run within k8s env
    port: 5432
    schema: amartha_loan_service
    username: <YOUR_USERNAME>
    password: <YOUR_PASSWORD>
    autoMigrate: true
cache:
  redis:
    host: localhost # To run in host machine
    # host: redis # To run within docker env
    # host: 10.100.168.2 # To run within k8s env
    port: 6379
    db: 0
    password: 
messaging:
  enabled: true # No-op if not using Kafka
  kafka:
    brokers: 
    - localhost:9092 # To run in host machine
    user:
    password:
    SSL:
      enabled: false # No-op if not using SSL
      certFile: ""
      keyFile: ""
      caFile: ""
      serverName: ""
smtp:
  enabled: true # No-op if not using SMTP
  mailHog:
    host: localhost # MailHog for local development
    port: 1025 # MailHog for local development
app:
  auth:
    excludedMethods: 
    - Login
    - Register
    - IsUserExist
    - RefreshToken

