namespaceOverride: common-dev
fullnameOverride: vault

server:
  image:
    repository: hashicorp/vault
    tag: 1.17.2
    pullPolicy: IfNotPresent
  logLevel: info
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "250m"
  readinessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true
    failureThreshold: 2
    initialDelaySeconds: 5
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
    port: 8200
  livenessProbe:
    enabled: true
    path: /v1/sys/health?standbyok=true
    initialDelaySeconds: 60
    failureThreshold: 2
    periodSeconds: 5
    successThreshold: 1
    timeoutSeconds: 3
    port: 8200
  service:
    type: ClusterIP
    port: 8200
  serviceAccount:
    create: true
    name: vault-sa
  nodeSelector: 
    kubernetes.io/hostname: kube-worker-02
  dataStorage:
    enabled: true
    size: 1Gi
    storageClass: local-worker-02
    mountPath: /vault/data
    accessModes: ReadWriteOnce
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  ha:
    enabled: true
    raft:
      enabled: true
      setNodeId: true
    replicas: 1
  extraEnvironmentVars:
    VAULT_ADDR: "http://0.0.0.0:8200"

injector:
  enabled: false

ui:
  enabled: true
  serviceType: ClusterIP
  servicePort: 8201
