# k create secret generic vault-token-secret --from-literal=token='<YOUR_TOKEN>' -n development
apiVersion: v1
kind: Secret
metadata:
  name: vault-secret-token
  namespace: common-dev
type: Opaque
data:
  token: <BASE64_ENCODED_TOKEN>