apiVersion: v1
kind: PersistentVolume
metadata:
  name: pgri-dev-redis
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-worker-02
  local:
    path: /mnt/k8s/pv/pgri-dev/redis
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - kube-worker-02
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis
  namespace: pgri-dev
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  volumeName: pgri-dev-redis
  storageClassName: local-worker-02