// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/ffauzann/loan-service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// MessagingRepository is an autogenerated mock type for the MessagingRepository type
type MessagingRepository struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *MessagingRepository) Publish(ctx context.Context, msg *model.Message) error {
	ret := _m.Called(ctx, msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *model.Message) error); ok {
		r0 = rf(ctx, msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMessagingRepository creates a new instance of MessagingRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMessagingRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MessagingRepository {
	mock := &MessagingRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
